//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.25 at 05:05:58 PM EDT 
//

package com.aptima.ddd.networktools.jxab;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{}Name&quot;/&gt;
 *         &lt;element ref=&quot;{}IsEngram&quot;/&gt;
 *         &lt;element ref=&quot;{}Cones&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "name", "isEngram", "cones" })
@XmlRootElement(name = "AttributeSensed")
public class AttributeSensed  implements Serializable {

	@XmlElement(name = "Cones", required = true)
	protected Cones cones;

	@XmlElement(name = "IsEngram")
	protected boolean isEngram;

	@XmlElement(name = "Name", required = true)
	protected String name;
	public AttributeSensed() {
		// TODO Auto-generated constructor stub
	}
	public AttributeSensed(String name, boolean isEngram, Cones cones) {
		super();
		this.name = name;
		this.isEngram = isEngram;
		this.cones = cones;
	}

	/**
	 * Gets the value of the cones property.
	 * 
	 * @return possible object is {@link Cones }
	 * 
	 */
	public Cones getCones() {
		return cones;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Gets the value of the isEngram property.
	 * 
	 */
	public boolean isIsEngram() {
		return isEngram;
	}

	/**
	 * Sets the value of the cones property.
	 * 
	 * @param value
	 *            allowed object is {@link Cones }
	 * 
	 */
	public void setCones(Cones value) {
		this.cones = value;
	}

	/**
	 * Sets the value of the isEngram property.
	 * 
	 */
	public void setIsEngram(boolean value) {
		this.isEngram = value;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

}
