//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.25 at 05:05:58 PM EDT 
//

package com.aptima.ddd.networktools.jxab;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{}Direction&quot;/&gt;
 *         &lt;element ref=&quot;{}Level&quot;/&gt;
 *         &lt;element ref=&quot;{}Extent&quot;/&gt;
 *         &lt;element ref=&quot;{}Spread&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "direction", "level", "extent", "spread" })
@XmlRootElement(name = "ConeType")
public class ConeType  implements Serializable {

	@XmlElement(name = "Direction", required = true)
	protected Direction direction;

	@XmlElement(name = "Extent")
	protected double extent;

	@XmlElement(name = "Level", required = true)
	protected String level;
	@XmlElement(name = "Spread")
	protected double spread;
	public ConeType() {
		// TODO Auto-generated constructor stub
	}
	public ConeType(Direction direction, String level, double extent,
			double spread) {
		super();
		this.direction = direction;
		this.level = level;
		this.extent = extent;
		this.spread = spread;
	}

	/**
	 * Gets the value of the direction property.
	 * 
	 * @return possible object is {@link Direction }
	 * 
	 */
	public Direction getDirection() {
		return direction;
	}

	/**
	 * Gets the value of the extent property.
	 * 
	 */
	public double getExtent() {
		return extent;
	}

	/**
	 * Gets the value of the level property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLevel() {
		return level;
	}

	/**
	 * Gets the value of the spread property.
	 * 
	 */
	public double getSpread() {
		return spread;
	}

	/**
	 * Sets the value of the direction property.
	 * 
	 * @param value
	 *            allowed object is {@link Direction }
	 * 
	 */
	public void setDirection(Direction value) {
		this.direction = value;
	}

	/**
	 * Sets the value of the extent property.
	 * 
	 */
	public void setExtent(double value) {
		this.extent = value;
	}

	/**
	 * Sets the value of the level property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLevel(String value) {
		this.level = value;
	}

	/**
	 * Sets the value of the spread property.
	 * 
	 */
	public void setSpread(double value) {
		this.spread = value;
	}

}
