//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.25 at 05:05:58 PM EDT 
//

package com.aptima.ddd.networktools.jxab;

import java.io.Serializable;
import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{}Name&quot;/&gt;
 *         &lt;element ref=&quot;{}Range&quot;/&gt;
 *         &lt;element ref=&quot;{}Intensity&quot;/&gt;
 *         &lt;element ref=&quot;{}Probability&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "name", "range", "intensity", "probability" })
@XmlRootElement(name = "Effect")
public class Effect  implements Serializable{

	@XmlElement(name = "Intensity", required = true)
	protected BigInteger intensity;

	@XmlElement(name = "Name", required = true)
	protected String name;

	@XmlElement(name = "Probability")
	protected double probability;

	@XmlElement(name = "Range")
	protected double range;
	public Effect() {
		super();
	}
	public Effect(String name, double range, BigInteger intensity,
			double probability) {
		super();
		this.name = name;
		this.range = range;
		this.intensity = intensity;
		this.probability = probability;
	}
	public Effect(String name, double range, Integer intensity,
			double probability) {
		super();
		this.name = name;
		this.range = range;
		this.intensity = BigInteger.valueOf(intensity);
		this.probability = probability;
	}

	/**
	 * Gets the value of the intensity property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getIntensity() {
		return intensity;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Gets the value of the probability property.
	 * 
	 */
	public double getProbability() {
		return probability;
	}

	/**
	 * Gets the value of the range property.
	 * 
	 */
	public double getRange() {
		return range;
	}

	/**
	 * Sets the value of the intensity property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setIntensity(BigInteger value) {
		this.intensity = value;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Sets the value of the probability property.
	 * 
	 */
	public void setProbability(double value) {
		this.probability = value;
	}

	/**
	 * Sets the value of the range property.
	 * 
	 */
	public void setRange(double value) {
		this.range = value;
	}

}
