//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.25 at 05:05:58 PM EDT 
//

package com.aptima.ddd.networktools.jxab;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{}Emitter&quot;/&gt;
 *         &lt;element ref=&quot;{}AttributeName&quot;/&gt;
 *         &lt;element ref=&quot;{}IsEngram&quot;/&gt;
 *         &lt;element ref=&quot;{}Levels&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "emitter", "attributeName", "isEngram",
		"levels" })
@XmlRootElement(name = "EmitterType")
public class EmitterType  implements Serializable{

	@XmlElement(name = "AttributeName", required = true)
	protected String attributeName;

	@XmlElement(name = "Emitter", required = true)
	protected Emitter emitter;

	@XmlElement(name = "IsEngram")
	protected boolean isEngram;
	@XmlElement(name = "Levels", required = true)
	protected Levels levels;
	public EmitterType() {
		super();
	}
	public EmitterType(Emitter emitter, String attributeName, boolean isEngram,
			Levels levels) {
		super();
		this.emitter = emitter;
		this.attributeName = attributeName;
		this.isEngram = isEngram;
		this.levels = levels;
	}

	/**
	 * Gets the value of the attributeName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAttributeName() {
		return attributeName;
	}

	/**
	 * Gets the value of the emitter property.
	 * 
	 * @return possible object is {@link Emitter }
	 * 
	 */
	public Emitter getEmitter() {
		return emitter;
	}

	/**
	 * Gets the value of the levels property.
	 * 
	 * @return possible object is {@link Levels }
	 * 
	 */
	public Levels getLevels() {
		return levels;
	}

	/**
	 * Gets the value of the isEngram property.
	 * 
	 */
	public boolean isIsEngram() {
		return isEngram;
	}

	/**
	 * Sets the value of the attributeName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAttributeName(String value) {
		this.attributeName = value;
	}

	/**
	 * Sets the value of the emitter property.
	 * 
	 * @param value
	 *            allowed object is {@link Emitter }
	 * 
	 */
	public void setEmitter(Emitter value) {
		this.emitter = value;
	}

	/**
	 * Sets the value of the isEngram property.
	 * 
	 */
	public void setIsEngram(boolean value) {
		this.isEngram = value;
	}

	/**
	 * Sets the value of the levels property.
	 * 
	 * @param value
	 *            allowed object is {@link Levels }
	 * 
	 */
	public void setLevels(Levels value) {
		this.levels = value;
	}

}
