//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.25 at 05:05:58 PM EDT 
//

package com.aptima.ddd.networktools.jxab;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{}Level&quot;/&gt;
 *         &lt;element ref=&quot;{}Variance&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "level", "variance" })
@XmlRootElement(name = "Levels")
public class Levels  implements Serializable{

	@XmlElement(name = "Level", required = true)
	protected String level;

	@XmlElement(name = "Variance")
	protected double variance;

	public Levels() {
		super();
	}
	public Levels(String level, double variance) {
		super();
		this.level = level;
		this.variance = variance;
	}

	/**
	 * Gets the value of the level property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLevel() {
		return level;
	}

	/**
	 * Gets the value of the variance property.
	 * 
	 */
	public double getVariance() {
		return variance;
	}

	/**
	 * Sets the value of the level property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLevel(String value) {
		this.level = value;
	}

	/**
	 * Sets the value of the variance property.
	 * 
	 */
	public void setVariance(double value) {
		this.variance = value;
	}

}
