//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.25 at 05:05:58 PM EDT 
//

package com.aptima.ddd.networktools.jxab;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the sandbox.test package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _AttributeName_QNAME = new QName("",
			"AttributeName");
	private final static QName _BooleanType_QNAME = new QName("", "BooleanType");
	private final static QName _DoubleType_QNAME = new QName("", "DoubleType");
	private final static QName _Extent_QNAME = new QName("", "Extent");
	private final static QName _IntegerType_QNAME = new QName("", "IntegerType");
	private final static QName _Intensity_QNAME = new QName("", "Intensity");
	private final static QName _IsEngram_QNAME = new QName("", "IsEngram");
	private final static QName _Level_QNAME = new QName("", "Level");
	private final static QName _MaxRange_QNAME = new QName("", "MaxRange");
	private final static QName _Name_QNAME = new QName("", "Name");
	private final static QName _Probability_QNAME = new QName("", "Probability");
	private final static QName _Range_QNAME = new QName("", "Range");
	private final static QName _SensorName_QNAME = new QName("", "SensorName");
	private final static QName _Spread_QNAME = new QName("", "Spread");
	private final static QName _StringType_QNAME = new QName("", "StringType");
	private final static QName _Variance_QNAME = new QName("", "Variance");
	private final static QName _VulnerabilityType_QNAME = new QName("",
			"VulnerabilityType");
	private final static QName _VX_QNAME = new QName("", "VX");
	private final static QName _VY_QNAME = new QName("", "VY");
	private final static QName _VZ_QNAME = new QName("", "VZ");
	private final static QName _X_QNAME = new QName("", "X");
	private final static QName _Y_QNAME = new QName("", "Y");
	private final static QName _Z_QNAME = new QName("", "Z");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: sandbox.test
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Attribute }
	 * 
	 */
	public Attribute createAttribute() {
		return new Attribute();
	}

	/**
	 * Create an instance of {@link AttributeCollectionType }
	 * 
	 */
	public AttributeCollectionType createAttributeCollectionType() {
		return new AttributeCollectionType();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "AttributeName")
	public JAXBElement<String> createAttributeName(String value) {
		return new JAXBElement<String>(_AttributeName_QNAME, String.class,
				null, value);
	}

	/**
	 * Create an instance of {@link AttributeSensed }
	 * 
	 */
	public AttributeSensed createAttributeSensed() {
		return new AttributeSensed();
	}

	/**
	 * Create an instance of {@link AttributesSensed }
	 * 
	 */
	public AttributesSensed createAttributesSensed() {
		return new AttributesSensed();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code
	 * >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "BooleanType")
	public JAXBElement<Boolean> createBooleanType(Boolean value) {
		return new JAXBElement<Boolean>(_BooleanType_QNAME, Boolean.class,
				null, value);
	}

	/**
	 * Create an instance of {@link CapabilityType }
	 * 
	 */
	public CapabilityType createCapabilityType() {
		return new CapabilityType();
	}

	/**
	 * Create an instance of {@link Cones }
	 * 
	 */
	public Cones createCones() {
		return new Cones();
	}

	/**
	 * Create an instance of {@link ConeType }
	 * 
	 */
	public ConeType createConeType() {
		return new ConeType();
	}

	/**
	 * Create an instance of {@link CustomAttribute }
	 * 
	 */
	public CustomAttribute createCustomAttribute() {
		return new CustomAttribute();
	}

	/**
	 * Create an instance of {@link CustomAttributesType }
	 * 
	 */
	public CustomAttributesType createCustomAttributesType() {
		return new CustomAttributesType();
	}

	/**
	 * Create an instance of {@link Direction }
	 * 
	 */
	public Direction createDirection() {
		return new Direction();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "DoubleType")
	public JAXBElement<Double> createDoubleType(Double value) {
		return new JAXBElement<Double>(_DoubleType_QNAME, Double.class, null,
				value);
	}

	/**
	 * Create an instance of {@link Effect }
	 * 
	 */
	public Effect createEffect() {
		return new Effect();
	}

	/**
	 * Create an instance of {@link Emitter }
	 * 
	 */
	public Emitter createEmitter() {
		return new Emitter();
	}

	/**
	 * Create an instance of {@link EmitterType }
	 * 
	 */
	public EmitterType createEmitterType() {
		return new EmitterType();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "Extent")
	public JAXBElement<Double> createExtent(Double value) {
		return new JAXBElement<Double>(_Extent_QNAME, Double.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "IntegerType")
	public JAXBElement<BigInteger> createIntegerType(BigInteger value) {
		return new JAXBElement<BigInteger>(_IntegerType_QNAME,
				BigInteger.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "Intensity")
	public JAXBElement<BigInteger> createIntensity(BigInteger value) {
		return new JAXBElement<BigInteger>(_Intensity_QNAME, BigInteger.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code
	 * >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "IsEngram")
	public JAXBElement<Boolean> createIsEngram(Boolean value) {
		return new JAXBElement<Boolean>(_IsEngram_QNAME, Boolean.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "Level")
	public JAXBElement<String> createLevel(String value) {
		return new JAXBElement<String>(_Level_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link Levels }
	 * 
	 */
	public Levels createLevels() {
		return new Levels();
	}

	/**
	 * Create an instance of {@link LocationType }
	 * 
	 */
	public LocationType createLocationType() {
		return new LocationType();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "MaxRange")
	public JAXBElement<Double> createMaxRange(Double value) {
		return new JAXBElement<Double>(_MaxRange_QNAME, Double.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "Name")
	public JAXBElement<String> createName(String value) {
		return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link Parameter }
	 * 
	 */
	public Parameter createParameter() {
		return new Parameter();
	}

	/**
	 * Create an instance of {@link Point }
	 * 
	 */
	public Point createPoint() {
		return new Point();
	}

	/**
	 * Create an instance of {@link PolygonType }
	 * 
	 */
	public PolygonType createPolygonType() {
		return new PolygonType();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "Probability")
	public JAXBElement<Double> createProbability(Double value) {
		return new JAXBElement<Double>(_Probability_QNAME, Double.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "Range")
	public JAXBElement<Double> createRange(Double value) {
		return new JAXBElement<Double>(_Range_QNAME, Double.class, null, value);
	}

	/**
	 * Create an instance of {@link Sensor }
	 * 
	 */
	public Sensor createSensor() {
		return new Sensor();
	}

	/**
	 * Create an instance of {@link SensorArrayType }
	 * 
	 */
	public SensorArrayType createSensorArrayType() {
		return new SensorArrayType();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "SensorName")
	public JAXBElement<String> createSensorName(String value) {
		return new JAXBElement<String>(_SensorName_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link SensorType }
	 * 
	 */
	public SensorType createSensorType() {
		return new SensorType();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "Spread")
	public JAXBElement<Double> createSpread(Double value) {
		return new JAXBElement<Double>(_Spread_QNAME, Double.class, null, value);
	}

	/**
	 * Create an instance of {@link StateName }
	 * 
	 */
	public StateName createStateName() {
		return new StateName();
	}

	/**
	 * Create an instance of {@link StateTableType }
	 * 
	 */
	public StateTableType createStateTableType() {
		return new StateTableType();
	}

	/**
	 * Create an instance of {@link StringListType }
	 * 
	 */
	public StringListType createStringListType() {
		return new StringListType();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "StringType")
	public JAXBElement<String> createStringType(String value) {
		return new JAXBElement<String>(_StringType_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link Value }
	 * 
	 */
	public Value createValue() {
		return new Value();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "Variance")
	public JAXBElement<Double> createVariance(Double value) {
		return new JAXBElement<Double>(_Variance_QNAME, Double.class, null,
				value);
	}

	/**
	 * Create an instance of {@link VelocityType }
	 * 
	 */
	public VelocityType createVelocityType() {
		return new VelocityType();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "VulnerabilityType")
	public JAXBElement<Object> createVulnerabilityType(Object value) {
		return new JAXBElement<Object>(_VulnerabilityType_QNAME, Object.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "VX")
	public JAXBElement<Double> createVX(Double value) {
		return new JAXBElement<Double>(_VX_QNAME, Double.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "VY")
	public JAXBElement<Double> createVY(Double value) {
		return new JAXBElement<Double>(_VY_QNAME, Double.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "VZ")
	public JAXBElement<Double> createVZ(Double value) {
		return new JAXBElement<Double>(_VZ_QNAME, Double.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "X")
	public JAXBElement<Double> createX(Double value) {
		return new JAXBElement<Double>(_X_QNAME, Double.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "Y")
	public JAXBElement<Double> createY(Double value) {
		return new JAXBElement<Double>(_Y_QNAME, Double.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "Z")
	public JAXBElement<Double> createZ(Double value) {
		return new JAXBElement<Double>(_Z_QNAME, Double.class, null, value);
	}

}
