//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.25 at 05:05:58 PM EDT 
//

package com.aptima.ddd.networktools.jxab;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{}SensorType&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "sensorType" })
@XmlRootElement(name = "Sensor")
public class Sensor  implements Serializable{

	@XmlElement(name = "SensorType", required = true)
	protected SensorType sensorType;

	public Sensor() {
		super();
	}

	public Sensor(SensorType sensorType) {
		super();
		this.sensorType = sensorType;
	}

	/**
	 * Gets the value of the sensorType property.
	 * 
	 * @return possible object is {@link SensorType }
	 * 
	 */
	public SensorType getSensorType() {
		return sensorType;
	}

	/**
	 * Sets the value of the sensorType property.
	 * 
	 * @param value
	 *            allowed object is {@link SensorType }
	 * 
	 */
	public void setSensorType(SensorType value) {
		this.sensorType = value;
	}

}
