//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.25 at 05:05:58 PM EDT 
//

package com.aptima.ddd.networktools.jxab;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{}SensorName&quot;/&gt;
 *         &lt;element ref=&quot;{}MaxRange&quot;/&gt;
 *         &lt;element ref=&quot;{}AttributesSensed&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "sensorName", "maxRange", "attributesSensed" })
@XmlRootElement(name = "SensorType")
public class SensorType  implements Serializable{

	@XmlElement(name = "AttributesSensed", required = true)
	protected AttributesSensed attributesSensed;

	@XmlElement(name = "MaxRange")
	protected double maxRange;

	@XmlElement(name = "SensorName", required = true)
	protected String sensorName;
	public SensorType() {
		// TODO Auto-generated constructor stub
	}
	public SensorType(String sensorName, double maxRange,
			AttributesSensed attributesSensed) {
		super();
		this.sensorName = sensorName;
		this.maxRange = maxRange;
		this.attributesSensed = attributesSensed;
	}

	/**
	 * Gets the value of the attributesSensed property.
	 * 
	 * @return possible object is {@link AttributesSensed }
	 * 
	 */
	public AttributesSensed getAttributesSensed() {
		return attributesSensed;
	}

	/**
	 * Gets the value of the maxRange property.
	 * 
	 */
	public double getMaxRange() {
		return maxRange;
	}

	/**
	 * Gets the value of the sensorName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSensorName() {
		return sensorName;
	}

	/**
	 * Sets the value of the attributesSensed property.
	 * 
	 * @param value
	 *            allowed object is {@link AttributesSensed }
	 * 
	 */
	public void setAttributesSensed(AttributesSensed value) {
		this.attributesSensed = value;
	}

	/**
	 * Sets the value of the maxRange property.
	 * 
	 */
	public void setMaxRange(double value) {
		this.maxRange = value;
	}

	/**
	 * Sets the value of the sensorName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSensorName(String value) {
		this.sensorName = value;
	}

}
