//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.25 at 05:05:58 PM EDT 
//

package com.aptima.ddd.networktools.jxab;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{}VX&quot;/&gt;
 *         &lt;element ref=&quot;{}VY&quot;/&gt;
 *         &lt;element ref=&quot;{}VZ&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "vx", "vy", "vz" })
@XmlRootElement(name = "VelocityType")
public class VelocityType implements Serializable{

	@XmlElement(name = "VX")
	protected double vx;

	@XmlElement(name = "VY")
	protected double vy;

	@XmlElement(name = "VZ")
	protected double vz;
	public VelocityType() {
		// TODO Auto-generated constructor stub
	}
	public VelocityType(double vx, double vy, double vz) {
		super();
		this.vx = vx;
		this.vy = vy;
		this.vz = vz;
	}

	/**
	 * Gets the value of the vx property.
	 * 
	 */
	public double getVX() {
		return vx;
	}

	/**
	 * Gets the value of the vy property.
	 * 
	 */
	public double getVY() {
		return vy;
	}

	/**
	 * Gets the value of the vz property.
	 * 
	 */
	public double getVZ() {
		return vz;
	}

	/**
	 * Sets the value of the vx property.
	 * 
	 */
	public void setVX(double value) {
		this.vx = value;
	}

	/**
	 * Sets the value of the vy property.
	 * 
	 */
	public void setVY(double value) {
		this.vy = value;
	}

	/**
	 * Sets the value of the vz property.
	 * 
	 */
	public void setVZ(double value) {
		this.vz = value;
	}

	
	public String toString() {
		return "( "+vx+", "+vy+", "+vz+" )";
	}

}
